### ISSUE TITLE
[Feature request] improve ReadMe, add new features

### ISSUE THREAD

**Issue by BachiMjavanadze** [Afrino-co/EfCoreUI#1]
This error occurs:

![image](https://github.com/Afrino-co/EfCoreUI/assets/38082501/9813b91a-b3d1-4f87-8c42-166600044d90)

reazon is that I've not installed:

`dotnet tool install --global dotnet-ef`

Please include this information on ReadMe.

Please add one more command: 

`add-migration + update`

in Visual Studio console i usually run:

`Add-Migration init; Update-Database`

your green console is very unreadable. make it extensible, or better yet, run commands in the native Visual Studio console, or make this feature customizable: some will prefer the native console, others will prefer yours.

Thanks! Awesome!

**Comment by masoodafar-web** [comment]
Hi dear  @BachiMjavanadze
Thank you for your effective communication, your tips have been applied to improve, so that by updating the extension, you can see the result in the output window.
But about ` add-migration + update` , if we receive significant feedback from other users, we will definitely add it to the extension.
We welcome your feedback.
